# -*- coding: utf-8 -*-
"""Patient_Heart_Rate_Monitoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KFcdcU1sBJ_Wf6erAlLQ1i3gAlvIwZXg

# Simulating Patient Heart Rate Monitoring

# Starter Code: Run the code below to start
"""

# Step 1: Import the random module
import random

# Step 2: Set up variables
normal_hr_min = 60
normal_hr_max = 100
minutes = 480
abnormal_readings = 0

# Step 3: Simulate heart rate readings over 480 minutes

# Loop through each minute of the 8-hour day
for minute in range(1, minutes + 1):

    # Generate a random heart rate between 55 and 110 bpm
    hr = random.randint(55, 110)

    # Print the current minute and heart rate reading
    print(f"Minute {minute}: Heart Rate = {hr}")

    # Check if the heart rate is outside the normal range (60–100 bpm)
    if hr < normal_hr_min or hr > normal_hr_max:

        # Print a warning message for abnormal readings
        print("  ⚠️ Abnormal heart rate detected!")

        # Increment the counter for abnormal readings
        abnormal_readings += 1

# Step 4: Print summary
print(f"\nTotal abnormal readings: {abnormal_readings}")
print(f"Percentage of time abnormal: {abnormal_readings / minutes * 100:.2f}%")

"""## Simulating POTS (Postural Orthostatic Tachycardia Syndrome)

POTS is a condition that affects circulation (blood flow) and is characterized by an excessive increase in heart rate when moving from lying down to standing up.

To simulate this:
- Assume the patient stands up every hour (i.e., at minute 60, 120, 180, ..., 480).
- When standing, simulate a temporary spike in heart rate (e.g., increase by 20–30 bpm).
- Flag these spikes as potential POTS episodes if the heart rate exceeds 100 bpm during standing.
- Track and summarize the number of suspected POTS episodes.

This extension helps you explore how specific conditions can be modeled in simulations.
"""

# Step 5: Simulate POTS episodes

# Initialize a counter to track the number of suspected POTS episodes
pots_episodes = 0

# Loop through each minute in the 8-hour monitoring period (480 minutes total)
for minute in range(1, minutes + 1):

    # Every 60 minutes (i.e., once per hour), simulate the patient standing up
    # This is done by checking if the current minute is divisible evenly by 60
    # Standing up may cause a temporary spike in heart rate for patients with POTS
    if minute % 60 == 0:
        # Simulate a heart rate spike due to standing, using a higher range
        hr = random.randint(75, 130)
        print(f"Minute {minute} (Standing): Heart Rate = {hr}")

        # If the heart rate exceeds 100 bpm during standing, flag it as a possible POTS episode
        if hr > 100:
            print("  ⚠️ Possible POTS episode detected!")
            pots_episodes += 1
    else:
        # For all other minutes, simulate a regular heart rate reading
        hr = random.randint(55, 110)
        print(f"Minute {minute}: Heart Rate = {hr}")

    # Check if the heart rate is outside the normal range (60–100 bpm)
    # Flag any abnormal readings and increment the abnormal counter
    if hr < normal_hr_min or hr > normal_hr_max:
        print("  ⚠️ Abnormal heart rate detected!")
        abnormal_readings += 1

# Step 6: Updated summary
print(f"\nTotal abnormal readings: {abnormal_readings}")
print(f"Percentage of time abnormal: {abnormal_readings / minutes * 100:.2f}%")
print(f"Suspected POTS episodes: {pots_episodes}")

"""## Preparing simulation data for use in Pandas (a revised version of step 5):

In this revised version of Step 5, we continue simulating heart rate readings over an 8-hour period, including elevated readings during standing events to model POTS. To prepare for analysis using the `pandas` library in Step 8, we now store each heart rate value in a list called `heart_rates`, and label each minute as either `"Normal"` or `"Standing"` in a separate list called `labels`. These lists allow us to structure the data into a DataFrame, making it easier to filter, analyze, and visualize patterns in heart rate behavior across time.

"""

# Step 7: Simulate POTS episodes and prepare data for analysis

# Initialize counters
pots_episodes = 0
abnormal_readings = 0

# Initialize storage lists for pandas (used in a later step)
heart_rates = []
labels = []

# Loop through each minute in the 8-hour monitoring period
for minute in range(1, minutes + 1):

    # Simulate standing every hour
    if minute % 60 == 0:
        hr = random.randint(75, 130)
        labels.append("Standing")  # Label this minute as a standing event
        print(f"Minute {minute} (Standing): Heart Rate = {hr}")

        # Check for suspected POTS episode
        if hr > 100:
            print("  ⚠️ Possible POTS episode detected!")
            pots_episodes += 1
    else:
        hr = random.randint(55, 110)
        labels.append("Normal")  # Label this minute as a normal event
        print(f"Minute {minute}: Heart Rate = {hr}")

    # Check for abnormal heart rate
    if hr < normal_hr_min or hr > normal_hr_max:
        print("  ⚠️ Abnormal heart rate detected!")
        abnormal_readings += 1

    # Store heart rate for later analysis
    heart_rates.append(hr)

"""## Organizing simulation data with Pandas

In this step, we use the `pandas` library to organize our heart rate simulation data into a structured table called a DataFrame. This allows us to label each minute as either a normal event or a standing event, and to flag abnormal heart rate readings and suspected POTS episodes using logical conditions. By storing the data in a tabular format, we can easily filter, analyze, and prepare it for visualization or export. This step introduces foundational data wrangling skills that will be essential as we move into more advanced modeling and plotting in later units.

"""

# Step 8: Use pandas to organize the simulation data

import pandas as pd

# Create a DataFrame from the simulation results
df = pd.DataFrame({
    'Minute': range(1, minutes + 1),
    'HeartRate': heart_rates,
    'Event': labels
})

# Add a column to flag abnormal readings
df['Abnormal'] = (df['HeartRate'] < normal_hr_min) | (df['HeartRate'] > normal_hr_max)

# Add a column to flag suspected POTS episodes
df['SuspectedPOTS'] = (df['Event'] == 'Standing') & (df['HeartRate'] > 100)

# Display the first few rows
df.head()

"""To modify this code, instead of just using the rule that any heart rate > 100 is flagged, the code should use a personalized baseline for the user. It should compare standing HR to the user’s recent resting baseline for example take the  rolling mean over 7 days, or a baseline estimate from sleep/rest periods. Also it should take into account some context, for example has the user taken coffee? or worked out today? has the user had enough sleep? this information would give us more context into the user's heart rate data and be able to flag POTS more accurately

### The example modified code:
"""

import random
import pandas as pd

# Step 1: Set up variables
minutes = 480                  # 8 hours/day
days = 14                      # simulate 14 days so we can use a 7-day rolling baseline
normal_hr_min = 60
normal_hr_max = 100

abnormal_readings = 0
pots_episodes = 0

# Baseline + POTS logic
baseline_window = 7 * minutes  # last 7 days worth of minutes (simple rolling window)
pots_delta = 30                # standing HR must be +30 bpm above baseline
pots_stand_threshold = 5       # must happen at least 5 standing-minutes per day

# Storage for pandas
all_days = []
all_minutes = []
heart_rates = []
events = []
coffee_today_list = []
workout_today_list = []
slept_well_list = []

# Step 2: Simulate days
for day in range(1, days + 1):

    # Simple context for the day (one value for the whole day)
    had_coffee = random.choice([True, False])
    worked_out = random.choice([True, False])
    slept_well = random.choice([True, False])

    stand_high_minutes = 0  # count how many standing minutes look "POTS-like" today

    for minute in range(1, minutes + 1):

        # Standing event once per hour (like your original code)
        standing = (minute % 60 == 0)

        # --- Build a heart rate (simple, but with context) ---
        if standing:
            hr = random.randint(75, 130)
            event = "Standing"
        else:
            hr = random.randint(55, 110)
            event = "Normal"

        # Context effects (very simple)
        if had_coffee:
            hr += 5
        if worked_out and not standing:
            hr += 10
        if not slept_well:
            hr += 5

        # Clamp to keep values realistic
        hr = max(35, min(hr, 180))

        # --- Personalized baseline: mean of recent "Normal" HRs (rolling) ---
        # Use only Normal minutes (not standing) to estimate resting baseline
        recent_normals = [
            heart_rates[i] for i in range(max(0, len(heart_rates) - baseline_window), len(heart_rates))
            if events[i] == "Normal"
        ]
        if len(recent_normals) >= 30:  # require some history
            baseline = sum(recent_normals) / len(recent_normals)
        else:
            baseline = 70  # fallback baseline early on

        # --- POTS-like check: relative rise during standing, and exclude workout confound ---
        if standing and (hr - baseline >= pots_delta) and (not worked_out):
            stand_high_minutes += 1

        # Abnormal HR (like original)
        if hr < normal_hr_min or hr > normal_hr_max:
            abnormal_readings += 1

        # Store rows
        all_days.append(day)
        all_minutes.append(minute)
        heart_rates.append(hr)
        events.append(event)
        coffee_today_list.append(had_coffee)
        workout_today_list.append(worked_out)
        slept_well_list.append(slept_well)

    # If the "high delta" persists enough standing minutes, flag a suspected episode for the day
    if stand_high_minutes >= pots_stand_threshold:
        pots_episodes += 1

# Step 3: Put into DataFrame
df = pd.DataFrame({
    "Day": all_days,
    "Minute": all_minutes,
    "HeartRate": heart_rates,
    "Event": events,
    "CoffeeToday": coffee_today_list,
    "WorkoutToday": workout_today_list,
    "SleptWell": slept_well_list
})

print(df.head())
print(f"\nTotal abnormal readings: {abnormal_readings}")
print(f"Percentage of time abnormal: {abnormal_readings / (days * minutes) * 100:.2f}%")
print(f"Suspected POTS episodes (days flagged): {pots_episodes}")

"""# Reset variables: Run the following code to clear previously stored values

"""

heart_rates = []
labels = []
abnormal_readings = 0
pots_episodes = 0

"""## Personalized Clinical Scenario: Caffeine, poor sleep and anxiety spikes
This simulation models a patient who:
- Sleeps from 2:00 AM to 6:00 AM (lower heart rate during sleep)
- Drinks coffee once in the morning (temporary HR increase)
- Has short exercise bursts (brief HR elevation)
- Experiences random stress/anxiety spikes (sudden, short HR jumps)

Why it’s meaningful:
This is realistic for many patients/young adults and shows how heart rate changes can be caused by lifestyle factors—not only disease—so monitoring needs context.

"""

import random

# Step 1: Set up variables
normal_hr_min = 60
normal_hr_max = 100

minutes = 24 * 60          # simulate 24 hours (1 day)
abnormal_readings = 0
stress_spikes = 0
exercise_events = 0

# Patient context (personalization)
had_coffee = True
slept_poorly = True

# Timing choices (in minutes since midnight)
sleep_start = 2 * 60       # 2:00 AM
sleep_end = 6 * 60         # 6:00 AM

coffee_time = 9 * 60       # 9:00 AM (coffee)
coffee_duration = 120      # effect lasts 2 hours

# Exercise: 2 short bursts in the day (example)
exercise_windows = [
    (17 * 60 + 10, 17 * 60 + 25),   # 5:10 PM to 5:25 PM
    (20 * 60 + 0, 20 * 60 + 10)     # 8:00 PM to 8:10 PM
]

# Stress settings
stress_chance = 0.03       # 3% chance each minute for a spike event
stress_duration = 3        # spike lasts 3 minutes
stress_timer = 0

# Step 2: Simulate heart rate readings
for minute in range(1, minutes + 1):
    minute_of_day = minute - 1  # 0..1439

    # Base HR depending on sleep vs awake
    if sleep_start <= minute_of_day < sleep_end:
        # Lower HR during sleep (more realistic range)
        hr = random.randint(50, 65)
        event = "Sleep"
    else:
        # Awake baseline range
        hr = random.randint(65, 90)
        event = "Normal"

    # Coffee effect (temporary increase)
    if had_coffee:
        if coffee_time <= minute_of_day < (coffee_time + coffee_duration):
            hr += 8
            event = "Coffee"

    # Poor sleep effect (slightly higher HR during the day)
    if slept_poorly and event != "Sleep":
        hr += 5

    # Exercise events (short bursts of higher HR)
    in_exercise = False
    for start, end in exercise_windows:
        if start <= minute_of_day < end:
            hr = random.randint(110, 150)  # exercise HR burst
            event = "Exercise"
            in_exercise = True
            break
    # Count exercise events once when they start
    if in_exercise and minute_of_day in [w[0] for w in exercise_windows]:
        exercise_events += 1

    # Stress spikes (random short spikes)
    # If already in a stress spike, keep HR elevated for a few minutes
    if stress_timer > 0:
        hr += 25
        event = "StressSpike"
        stress_timer -= 1
    else:
        # Randomly start a new spike (avoid starting during exercise)
        if (not in_exercise) and random.random() < stress_chance:
            stress_timer = stress_duration - 1  # current minute counts as 1
            hr += 25
            event = "StressSpike"
            stress_spikes += 1

    # Clamp HR to plausible limits
    hr = max(35, min(hr, 190))

    # Print the current minute, HR, and event label
    print(f"Minute {minute:4d}: Heart Rate = {hr:3d} | Event = {event}")

    # Abnormal flag (same logic as original, but now with context)
    if hr < normal_hr_min or hr > normal_hr_max:
        print("  ⚠️ Abnormal heart rate detected!")
        abnormal_readings += 1

# Step 3: Summary
print("\n=== Daily Summary ===")
print(f"Total abnormal readings: {abnormal_readings}")
print(f"Percentage of time abnormal: {abnormal_readings / minutes * 100:.2f}%")
print(f"Exercise events simulated: {exercise_events}")
print(f"Stress spikes simulated: {stress_spikes}")
print(f"Coffee included: {had_coffee}")
print(f"Poor sleep included: {slept_poorly}")